# http://travis-ci.org/#!/ashleysommer/stdeb3
language: generic #Not python, because we use python inside docker
dist: xenial
services:
  - docker
env:
  global:
    - ENV1=test1
  matrix:
    - DEBIAN_VERSION=jessie
    - DEBIAN_VERSION=stretch

before_install:
  - mkdir -p /tmp/output
  - chmod 777 /tmp/output
  - docker pull ashleysommer/stdeb3:$DEBIAN_VERSION


before_script:
  - docker run -v /tmp/output:/home/stdeb3/output -t -i ashleysommer/stdeb3:$DEBIAN_VERSION
  - ls -lah /tmp/output
