language: generic
dist: xenial
services:
- docker
env:
  global:
  - ENV1=test1
  - secure: RLZpoFMSnDk2OYS/f8f47yRySB7dyOKJb96qgylp4Jw48UZ5ktswxDEAIdBjIvX6mi9MTTbaCFIvrdAAxH8qbOkWY3usi9DTpvJlbZNpKw+C08m+x5leR+OZohOPAQGXaGP617nqslcqC6BMI01gxz45BPi3nj/gyoNR4Te5bPsRQHyPAOIUJ1pxSXnpg8a48kc4XmrvJgTxAQFQ0upQwVFfOCm6pqZCrMl3posOWBP3R+BKZ/tWMylg8go1D1F1JJ4Ef8x7WQiZ/w3CjSLD3+P+29vRDzO0Xe7LWkgAOCeUmB8lzmmlHXluPRxiIAp7ACFTdHaA4Y1TQjA/2rnwoeAyZ27jF9NHNiIgKJ17H4HwBZ01OLA5PgW2NZSqjJ82W4huF6Uz50J3c3ojkiD/WinCc7Gh8oWck+fSFoXc3PJO2vioPb6YT/tJog+xwiSBRauqB1ihTkxAbf5YZsrZeYyNRT/Uc30QUpozTcXqsWSnMxZxn4+RGY/TzyVIqVW0SJ8SCTJ1tPRsq1GEli0XaPyFBYdkZ4BHNQKBGg5TbGOKjrKV66FMlEeFokSjGUVM2Swwz3g7ksUYqxhjvF1vQnQFcisLMkVuz0MNfeQPS93tVbG3+O8qn+PhMzEShpTMXMofstvB6EHSG7l0p6t1BOYRmiLIaPBbnL8q6VQn10k=
  matrix:
  - DEBIAN_VERSION=jessie STDEB3_SIGN_RESULTS=0 STDEB3_EXTRA_ARGS=""
  - DEBIAN_VERSION=stretch STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=10.2.5 --dh-compat=10"
  - DEBIAN_VERSION=buster STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=11.1.6 --dh-compat=11"
before_install:
- openssl aes-256-cbc -K $encrypted_e060ef17c1b2_key -iv $encrypted_e060ef17c1b2_iv
  -in secret_key.asc.enc -out /tmp/secret_key.asc -d
- mkdir -p /tmp/output
- chmod 777 /tmp/output
- docker pull ashleysommer/stdeb3:$DEBIAN_VERSION
before_script:
- docker run -v $(pwd)/docker-script.sh:/home/stdeb3/docker-script.sh  -v /tmp/secret_key.asc:/tmp/secret_key.asc
  -v /tmp/output:/home/stdeb3/output -e GPG_SECRET_KEY="/tmp/secret_key.asc" -e GPG_SECRET_KEY_PASSPHRASE="${GPG_SECRET_KEY_PASSPHRASE}"
  -e STDEB3_SIGN_RESULTS="$STDEB3_SIGN_RESULTS" -e STDEB3_EXTRA_ARGS="$STDEB3_EXTRA_ARGS"
  -t -i ashleysommer/stdeb3:$DEBIAN_VERSION
- ls -lah /tmp/output
deploy:
  provider: releases
  api_key:
    secure: R5nVWEUmG7Y2/Y1TNhwSQ0Qixv8ARPf78hkX1TNBkm49254S0tpcdHBCoSd0bpsLpMPtwh9OOE7wzY8ns1MwJ7ZKrx9H7Axi8q2WeFaiV7zwIfd3WThviYJ40dKtCuDX2m88jZgE1/bF8MRKr2rVBLPfS5O8FK+ZcmEUV5L71CFYAR0zVo/6G94GXNTw44UhNFgkSWtDJuhPVYGtnvUCVkMtv4ymFgwAtSww0rJ82sdphND5cn25T5G9RdePTQkki3MM5d29uDEGVP244baiQkyTt0XjtltNX+HdpX3A2TFRtT54gdypnElU2WfEHjUaoCYKZ++/+F1xlYwKtIWx+QSv3qILrKTc6+3rFVryp541k4Q34Ox5vsYUXpu2O91AhhXYrwkmhyAYPQftslP/yxc0xMogpabX38BX0HZ4N4+fUcelkW9LiIxv7qT266f+kvCtSwdi8NMrpnlWliooGX33fOXIb3Gh21xO56yM804S2x+cU9qvjlH6ktzZJ5NDTRESTfMUNQ5jsKRjdotQpiDOsZLySsPycEOJioUe+qtazQ3pdaWXLyiuQ7eADrZOYledY1jX8ojo8NK9ZG5VsZYpgRFjEkKJLsMCrJTm8I1DuMSo0PU9Te0+meKRNQBG2CyuObig7XEgPYdRAfst4Ri9hTf2/gcWbunqrI6GVOc=
  file: "/tmp/output/*.deb"
  skip_cleanup: true
  on:
    tags: true
